<?php

namespace Rutatiina\Banking\Seeders;

use Illuminate\Database\Seeder;
use Rutatiina\Banking\Models\Account;

class BankAccountsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Account::insert(
            array (
                0 =>
                    array (
                        'id' => 2,
                        'created_at' => NULL,
                        'updated_at' => NULL,
                        'deleted_at' => NULL,
                        'tenant_id' => 44,
                        'created_by' => NULL,
                        'external_key' => NULL,
                        'financial_account_code' => 0,
                        'type' => NULL,
                        'bank_id' => 1,
                        'name' => 'Test Bank account',
                        'number' => '123456789',
                        'code' => '101',
                        'currency' => 'UGX',
                        'routing_number' => NULL,
                        'swift_code' => NULL,
                        'description' => 'This is a test account',
                        'primary' => 1,
                        'active' => NULL,
                    ),
                1 =>
                    array (
                        'id' => 3,
                        'created_at' => '2019-05-23 14:30:32',
                        'updated_at' => '2019-08-13 09:52:05',
                        'deleted_at' => '2019-08-13 09:52:05',
                        'tenant_id' => 1,
                        'created_by' => NULL,
                        'external_key' => NULL,
                        'financial_account_code' => 823,
                        'type' => 'bank_account',
                        'bank_id' => 1,
                        'name' => 'Gilbert Testing',
                        'number' => '123456789456',
                        'code' => 'UBA',
                        'currency' => 'UGX',
                        'routing_number' => NULL,
                        'swift_code' => NULL,
                        'description' => 'UBA bank',
                        'primary' => 1,
                        'active' => 1,
                    ),
                2 =>
                    array (
                        'id' => 4,
                        'created_at' => '2019-05-30 19:19:35',
                        'updated_at' => '2019-08-13 09:54:03',
                        'deleted_at' => '2019-08-13 09:54:03',
                        'tenant_id' => 1,
                        'created_by' => NULL,
                        'external_key' => NULL,
                        'financial_account_code' => 824,
                        'type' => NULL,
                        'bank_id' => 1,
                        'name' => 'Gilbert Rutatiina',
                        'number' => '789456123',
                        'code' => '102',
                        'currency' => 'UGX',
                        'routing_number' => NULL,
                        'swift_code' => NULL,
                        'description' => 'UBA account',
                        'primary' => NULL,
                        'active' => 1,
                    ),
                3 =>
                    array (
                        'id' => 5,
                        'created_at' => '2019-07-18 16:15:30',
                        'updated_at' => '2019-08-13 09:54:20',
                        'deleted_at' => '2019-08-13 09:54:20',
                        'tenant_id' => 1,
                        'created_by' => NULL,
                        'external_key' => NULL,
                        'financial_account_code' => 828,
                        'type' => NULL,
                        'bank_id' => 1,
                        'name' => 'Gilbert Rutatiina',
                        'number' => '123456789456',
                        'code' => 'DTB',
                        'currency' => 'UGX',
                        'routing_number' => NULL,
                        'swift_code' => NULL,
                        'description' => 'DTB',
                        'primary' => 1,
                        'active' => 1,
                    ),
                4 =>
                    array (
                        'id' => 6,
                        'created_at' => '2019-07-18 16:19:10',
                        'updated_at' => '2019-07-18 16:19:10',
                        'deleted_at' => NULL,
                        'tenant_id' => 46,
                        'created_by' => NULL,
                        'external_key' => NULL,
                        'financial_account_code' => 829,
                        'type' => NULL,
                        'bank_id' => 1,
                        'name' => 'Gilbert Rutatiina',
                        'number' => '123456789456',
                        'code' => 'DTB',
                        'currency' => 'UGX',
                        'routing_number' => NULL,
                        'swift_code' => NULL,
                        'description' => 'DTB',
                        'primary' => 1,
                        'active' => 1,
                    ),
                5 =>
                    array (
                        'id' => 7,
                        'created_at' => '2019-07-18 16:29:26',
                        'updated_at' => '2019-07-18 17:15:32',
                        'deleted_at' => '2019-07-18 17:15:32',
                        'tenant_id' => 46,
                        'created_by' => NULL,
                        'external_key' => NULL,
                        'financial_account_code' => 830,
                        'type' => NULL,
                        'bank_id' => 1,
                        'name' => 'Account name Updated',
                        'number' => 'Account number',
                        'code' => 'Account code (optional)',
                        'currency' => 'UGX',
                        'routing_number' => NULL,
                        'swift_code' => NULL,
                        'description' => 'Account description',
                        'primary' => NULL,
                        'active' => 1,
                    ),
                6 =>
                    array (
                        'id' => 8,
                        'created_at' => '2019-07-19 16:40:01',
                        'updated_at' => '2019-07-19 16:40:29',
                        'deleted_at' => NULL,
                        'tenant_id' => 46,
                        'created_by' => NULL,
                        'external_key' => '_TESTING005_',
                        'financial_account_code' => 833,
                        'type' => NULL,
                        'bank_id' => 1,
                        'name' => 'Account name Updated',
                        'number' => 'Account number',
                        'code' => 'Account code (optional)',
                        'currency' => 'UGX',
                        'routing_number' => NULL,
                        'swift_code' => NULL,
                        'description' => 'Account description',
                        'primary' => NULL,
                        'active' => 1,
                    ),
                7 =>
                    array (
                        'id' => 9,
                        'created_at' => '2019-08-12 19:04:22',
                        'updated_at' => '2019-08-12 19:04:22',
                        'deleted_at' => NULL,
                        'tenant_id' => 47,
                        'created_by' => 2,
                        'external_key' => NULL,
                        'financial_account_code' => 839,
                        'type' => NULL,
                        'bank_id' => 1,
                        'name' => 'TOR3M Investment Club',
                        'number' => '01691116730501',
                        'code' => NULL,
                        'currency' => 'UGX',
                        'routing_number' => NULL,
                        'swift_code' => NULL,
                        'description' => 'DFCU Bank Account',
                        'primary' => 1,
                        'active' => 1,
                    ),
                8 =>
                    array (
                        'id' => 10,
                        'created_at' => '2019-08-12 19:05:45',
                        'updated_at' => '2019-08-12 19:05:45',
                        'deleted_at' => NULL,
                        'tenant_id' => 47,
                        'created_by' => 2,
                        'external_key' => NULL,
                        'financial_account_code' => 840,
                        'type' => NULL,
                        'bank_id' => 1,
                        'name' => 'Gilbert Rutatiina',
                        'number' => '123456789456',
                        'code' => NULL,
                        'currency' => 'UGX',
                        'routing_number' => NULL,
                        'swift_code' => NULL,
                        'description' => NULL,
                        'primary' => NULL,
                        'active' => 1,
                    ),
                9 =>
                    array (
                        'id' => 11,
                        'created_at' => '2019-08-12 19:16:54',
                        'updated_at' => '2019-08-12 19:16:54',
                        'deleted_at' => NULL,
                        'tenant_id' => 47,
                        'created_by' => 2,
                        'external_key' => NULL,
                        'financial_account_code' => 841,
                        'type' => NULL,
                        'bank_id' => 1,
                        'name' => 'Gilbert Rutatiina',
                        'number' => '123456789456',
                        'code' => NULL,
                        'currency' => 'UGX',
                        'routing_number' => NULL,
                        'swift_code' => NULL,
                        'description' => NULL,
                        'primary' => NULL,
                        'active' => 1,
                    ),
                10 =>
                    array (
                        'id' => 12,
                        'created_at' => '2019-08-13 09:56:32',
                        'updated_at' => '2019-08-13 09:56:32',
                        'deleted_at' => NULL,
                        'tenant_id' => 1,
                        'created_by' => 2,
                        'external_key' => NULL,
                        'financial_account_code' => 842,
                        'type' => NULL,
                        'bank_id' => 3,
                        'name' => 'Gilbert Rutatiina',
                        'number' => '123456789456',
                        'code' => NULL,
                        'currency' => 'UGX',
                        'routing_number' => NULL,
                        'swift_code' => NULL,
                        'description' => 'dfcu bank',
                        'primary' => 1,
                        'active' => 1,
                    ),
                11 =>
                    array (
                        'id' => 13,
                        'created_at' => '2019-08-23 13:56:36',
                        'updated_at' => '2019-08-23 13:56:36',
                        'deleted_at' => NULL,
                        'tenant_id' => 1,
                        'created_by' => 2,
                        'external_key' => NULL,
                        'financial_account_code' => 843,
                        'type' => NULL,
                        'bank_id' => 5,
                        'name' => 'testing account',
                        'number' => '8753241',
                        'code' => NULL,
                        'currency' => 'UGX',
                        'routing_number' => NULL,
                        'swift_code' => NULL,
                        'description' => 'UBA bank account',
                        'primary' => NULL,
                        'active' => 1,
                    ),
                12 =>
                    array (
                        'id' => 15,
                        'created_at' => '2019-08-23 14:09:06',
                        'updated_at' => '2019-08-23 14:09:06',
                        'deleted_at' => NULL,
                        'tenant_id' => 1,
                        'created_by' => 2,
                        'external_key' => NULL,
                        'financial_account_code' => 845,
                        'type' => NULL,
                        'bank_id' => 7,
                        'name' => 'Speeda Finance',
                        'number' => '4364576789',
                        'code' => NULL,
                        'currency' => 'UGX',
                        'routing_number' => NULL,
                        'swift_code' => NULL,
                        'description' => 'Trust Finance Bank',
                        'primary' => NULL,
                        'active' => 1,
                    ),
                13 =>
                    array (
                        'id' => 16,
                        'created_at' => '2019-11-27 17:15:59',
                        'updated_at' => '2019-11-27 17:15:59',
                        'deleted_at' => NULL,
                        'tenant_id' => 1,
                        'created_by' => 2,
                        'external_key' => NULL,
                        'financial_account_code' => 846,
                        'type' => NULL,
                        'bank_id' => 3,
                        'name' => 'Tor3m Investment',
                        'number' => '75636241144',
                        'code' => NULL,
                        'currency' => 'ALK',
                        'routing_number' => NULL,
                        'swift_code' => NULL,
                        'description' => NULL,
                        'primary' => NULL,
                        'active' => 1,
                    ),
            )
        );
    }
}
